
version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_sk
        description: "The primary key for this table"
        data_tests:
          - unique
      - name: first_name
      - name: last_name
      - name: email
      - name: address_line
      - name: city
      - name: state
      - name: zip_code    
  - name: dim_product
    columns:
      - name: product_sk
        description: "The primary key for this table"
        data_tests:
          - unique
      - name: product_id
      - name: product_name
      - name: category
      - name: brand  
  - name: dim_seller
    columns:
      - name: seller_sk
        description: "The primary key for this table"
        data_tests:
          - unique
      - name: seller_id
      - name: store_name
      - name: rating
      - name: joined_date
      - name: seller_tier  
